Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace s3cr3tx.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Forgot.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using s3cr3tx.Models;
using System.Data.SqlClient;
using System.Security.Cryptography;
using System.Web;
using System.Net;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Net.Mail;
//using Microsoft.Data.SqlClient;


namespace s3cr3tx.Pages
{
    //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ForgotModel : PageModel
    {
        
        public string _message = @"";
        //private readonly ILogger<ForgotModel> _logger;
        public s3cr3tx.Models.Forgot forgotCurrent;
        public s3cr3tx.Models.ForgotDbContext ForgotContext;
        public string _output;

        public ForgotModel(s3cr3tx.Models.ForgotDbContext forgotDbContext)
        {
            ForgotContext = forgotDbContext;
            forgotCurrent = new Forgot();
        }

        public void OnPostView()
        {
            try
            {
                HttpRequest Request = HttpContext.Request;
                if (Request.Form.TryGetValue("forgotCurrent.member_email", out Microsoft.Extensions.Primitives.StringValues Email))
                {

                    forgotCurrent.member_email = Email[0].ToLower();
                    string strConnection = @"Data Source=.;Integrated Security=SSPI;Initial Catalog=s3cr3tx";

                    SqlConnection sql3 = new SqlConnection(strConnection);
                    SqlCommand command3 = new SqlCommand();
                    command3.CommandText = @"dbo.usp_tbl_member_sel_email";
                    command3.CommandType = System.Data.CommandType.StoredProcedure;
                    SqlParameter p5 = new SqlParameter(@"email", forgotCurrent.member_email);
                    //SqlParameter p4 = new SqlParameter(@"member_code", strResult);
                    command3.Parameters.Add(p5);
                    //command2.Parameters.Add(p4);
                    DataSet dataSet = new DataSet();
                    SqlDataAdapter da = new SqlDataAdapter();
                    using (sql3)
                    {
                        sql3.Open();
                        command3.Connection = sql3;
                        da.SelectCommand = command3;
                        da.Fill(dataSet);
                    }
                    if (dataSet.Tables.Count >0)
                    { 
                    //create member object
                    Member member = new Member()
                    {
                        id = (long)dataSet.Tables[0].Rows[0].ItemArray[0],
                        email = dataSet.Tables[0].Rows[0].ItemArray[1].ToString(),
                        Code = dataSet.Tables[0].Rows[0].ItemArray[2].ToString(),
                        ConfirmCode = @"",
                        FirstName = dataSet.Tables[0].Rows[0].ItemArray[3].ToString(),
                        LastName = dataSet.Tables[0].Rows[0].ItemArray[4].ToString(),
                        regcode = dataSet.Tables[0].Rows[0].ItemArray[5].ToString(),
                        created = (DateTime)dataSet.Tables[0].Rows[0].ItemArray[6],
                        updated = (DateTime)dataSet.Tables[0].Rows[0].ItemArray[7],
                        enabled = (bool)dataSet.Tables[0].Rows[0].ItemArray[8],
                        confirmed = (bool)dataSet.Tables[0].Rows[0].ItemArray[9],
                        country = dataSet.Tables[0].Rows[0].ItemArray[10].ToString(),
                        state = dataSet.Tables[0].Rows[0].ItemArray[11].ToString(),
                        gender = dataSet.Tables[0].Rows[0].ItemArray[12].ToString(),
                        mobile = dataSet.Tables[0].Rows[0].ItemArray[13].ToString(),
                        MobileCarrier = dataSet.Tables[0].Rows[0].ItemArray[14].ToString(),
                        city = dataSet.Tables[0].Rows[0].ItemArray[15].ToString(),
                        zipcode = dataSet.Tables[0].Rows[0].ItemArray[16].ToString(),
                        address = dataSet.Tables[0].Rows[0].ItemArray[17].ToString(),
                        address2 = dataSet.Tables[0].Rows[0].ItemArray[18].ToString()
                    };
                    string strIP = @"";
                    if (HttpContext.Connection.RemoteIpAddress is not null)
                    {
                        IPAddress iP = HttpContext.Connection.RemoteIpAddress;
                        strIP = iP.ToString();
                    }
                    if (member.confirmed.Equals(true) && (member.enabled.Equals(true)))
                    {
                        //store the forgot data
                        SqlConnection sql4 = new SqlConnection(strConnection);
                        SqlCommand command4 = new SqlCommand();
                        command4.CommandText = @"dbo.usp_tbl_forgot_ins";
                        command4.CommandType = System.Data.CommandType.StoredProcedure;
                        SqlParameter p73 = new SqlParameter(@"member_id", member.id);
                        SqlParameter p71 = new SqlParameter(@"member_email", member.email);
                        SqlParameter p72 = new SqlParameter(@"member_token", forgotCurrent.member_code);
                        SqlParameter p74 = new SqlParameter(@"session_start", forgotCurrent.session_start);
                        SqlParameter p77 = new SqlParameter(@"session_end", forgotCurrent.code_expires);
                        SqlParameter p78 = new SqlParameter(@"member_ip", strIP);
                        command4.Parameters.Add(p71);
                        command4.Parameters.Add(p73);
                        command4.Parameters.Add(p72);
                        command4.Parameters.Add(p74);
                        command4.Parameters.Add(p77);
                        command4.Parameters.Add(p78);
                        int lngResult4 ;
                        using (sql4)
                        {
                            sql4.Open();
                            command4.Connection = sql4;
                            lngResult4 = (int)command4.ExecuteNonQuery();
                        }
                        if (lngResult4.Equals(0))
                        {
                            forgotCurrent.Output = @"Something went wrong.";
                            return;
                        }
                        else
                        {


                            Member _member = new Member();
                            MailMessage mail = new MailMessage();
                            mail.From = new MailAddress(@"support@s3cr3tx.com");
                            mail.Sender = new MailAddress(@"support@s3cr3tx.com");
                            mail.Subject = @"s3cr3tx account verification";
                            mail.To.Add(new MailAddress(forgotCurrent.member_email));
                            mail.IsBodyHtml = true;
                            mail.Body = @"Dear " + member.FirstName + @",<br/><br/>Please click the following link to reset your password: <a href='https://s3cr3tx.com/Freset?=" + System.Web.HttpUtility.UrlEncode(forgotCurrent.member_email) + @"_" + forgotCurrent.member_code + "'>https://s3cr3tx.com/Freset?=" + System.Web.HttpUtility.UrlEncode(forgotCurrent.member_email) + @"_" + forgotCurrent.member_code + @"</a><br/><br/>For your account protection, the link will only be active for 20 minutes. <br/><br/>Thank you!<br/><br/>s3cr3tx sales@gratitech.com";
                            SmtpClient smtp = new SmtpClient();
                            smtp.EnableSsl = true;
                            smtp.Host = GetS3cr3txD(@"SD8d/1ZiIFiNWRiGUYbXbt6fdtOppU3KOipsr5zGlY+Wk/VyHYiOMynMhwvZgv94Xkkewc0ZW7CW/zJ14JaTfLdNDGzeoHTV+Ae/SpTIsmZkLvMX9nkA/HY7F6PzlP96+5gfQkaWufkLEZ19KwdkhOpwJDTUgEOBOZ4LxCH5tQ0ZwrXhH8pHII2mlNkV+zQQAfPjJvBUiiSyk3UoMTw8NZBfYhi9xmFbgkNbFjKO4XUXTxhcFXcikepf80hWwEdZx7ZUKs+mT8us/boGgXvzolyjQZEqBI4+4XeMZ5N5DbBqMWNCy0Fu9kz11ncz+wJUJmOxorYnecPhMuu22AYR0M3tiW65Pb2i9cyzp52pqhCrSpfs7IOlLEmlfZWFINWYXoTvk3MfzgQKH7qYrTxfLoY8uUnQTJIxIR5Lacwab/F90bhtAqyxFwTFTI3zl+czXpw1JxQXcD+Uaq6XggkQcxq1OgdsmCSDAF6Wmu9iEjDxUbAG2A2vbXGE/N6xkGsU7s89PR7jdgdLk6ITFx7QLEt4hehStKLP/NetljEJevz7rgMVWsiwTELhZHqfZjxw/W3w/AR7Pnt3seVJbpPhy9zOXGF0va0BqWdcnPa1fp0Uo9NV6Oqnxf04vexg1E6mXQQGUpWdGbVIxWrz3JkwdUgxh/ooVwZcmpMxmo1Pil0=");
                            smtp.Credentials = new NetworkCredential(GetS3cr3txD(@"V4r2dhIxgnJx6395snHcuvuorVqc+UDasFhCZmgshLxQir9VV3pasUtRwJxd186dSNwbNq4WMt0hb+KOpKBsmNoblLOdY8+hZJpG5vislfztBfh2vWt51CdQApCxxym7Jx8Qx8HfACKNiw02RVjW5Rokv/M14chV8doWM0TXI1kXu7ziHYcI44OH2siR799pwigb2V82+D1aaO/rEiciZa1ZI0GVvCWRwqpz90YEImWbWEGx/FugE9E7WMYxr9kj0iREPImqJztv0xDJsOnZnNTa+m2GWb0XqDak6ujHOFdloWSqfk2YspU69U0a7vR7zOZrP7yk8mYP7eMd/QTEl92aYhLeuOrNjLQKdg+HIK7y2CFyKul+O3rN/Xe6r2QzdZ2R5RMl0uSdJEcCInJBCCkCdHZu1Dn5n5Hcj0/CHFE/bhGK23L5frlysMRIZZUGVWGAL/5JsF6tUfTkPV8nnyJXWgASaMVR6St8jolp4GutYCtP3drVk0ZI4xwo090uU/WYAxWrVv/AnPqT+mx42JCyouYnB4LnzZmUYUE8N/H6sOVtqx0AlPeDRxM6/BKAB+Rib7fi92lWbZr25pX0x5POdMIgifvJfxzpfud0y/LcgJ+3AqG4sDguNqYk5rLiCaaDDht10KC+5GA11fHzEZpgCDTgKVvejS0RzicT9sA="), GetS3cr3txD(@"DrJciccoic0dhIy8s+4QTqOHsjR3HFpxb92ea5spPF9dovYVOmF1kA3haNfX39U3QV+mK7xdvFcFl2QTCCMglICOKTjilwZixKoWZDe8vNauAFtkftBdF2OZM7mb7uzOkGhHJtGP7XtN+DLP587lTq3OaHvklIwhsd01Fgnd6ceMHAcJMY3wdCtVN4jJrm/1Vx4w51imrvlHdzEqc+IjBk8eh2P40Z73aT5NmodMsikXOm4f888d2rTwDF3984Y9jHmv7ogMu6ALS7ZYP2NSXFO1R9RoSRuC+BsLjl4oTNEy2hqAAgDyV457YT6EgrEYp3iOMpi+B187F+SccG4NLEuqWR4W5mg8BoopoUejKrGQbcvAmQwpP+7hp3WXhZZKJEKhqGRf2OiXL61M6evpK70OQQK8/3z2VmOM8lRXZxr+BIP22+KLX85IWOLa0F+FUEtJRf0FM7g7EKf2wegvI+69pBm0s3jFzkey5yMOaUGzBlUdWUBcTJeJQia3/KvdZ+cMpY0en/3oozcxMuciCNvqk5JU2wH7f1H+/0eDqK/Wkqg1c9w5/acIXMZC1x6fpWSVrLMk2x63sHYvdb96h/d/Oi1SvaOGT7XD6erRThf0rhGUoCKgohTsRIn60z9Bd7O++nNbIcs/FZKcDTB7gnXj+xAoArZbOfE7vevfmEI="));

Pages/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using s3cr3tx.Models;
using System.Data.SqlClient;
using System.Data;
using System.Security.Cryptography;


namespace s3cr3tx.Pages
{
    //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class LogoutModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
        public string _message = @"";
        private readonly ILogger<LogoutModel> _logger;

        public LogoutModel(ILogger<LogoutModel> logger)
        { 
                _logger = logger;
        }

        public void OnGet()
        {
            try
            {
                if (Request.Cookies.TryGetValue(@"s3cr3tx", out string? strValue))
                {
                    Response.Cookies.Delete(@"s3cr3tx");
                    //decrypt the cookie value
                    string strSessionID = Controllers.uspEncDec.Dec(@"sales@gratitech.com", strValue);
                    //get the session object
                    string strConnection = @"Data Source=.;Integrated Security=SSPI;Initial Catalog=s3cr3tx";

                    SqlConnection sql = new SqlConnection(strConnection);
                    SqlCommand command = new SqlCommand();
                    command.CommandText = @"dbo.usp_tbl_member_sessions_selCode";
                    command.CommandType = System.Data.CommandType.StoredProcedure;
                    SqlParameter p5 = new SqlParameter(@"ID", strSessionID);
                    //SqlParameter p4 = new SqlParameter(@"member_code", strResult);
                    command.Parameters.Add(p5);
                    //command2.Parameters.Add(p4);
                    DataSet dataSet = new DataSet();
                    SqlDataAdapter da = new SqlDataAdapter();
                    using (sql)
                    {
                        sql.Open();
                        command.Connection = sql;
                        da.SelectCommand = command;
                        da.Fill(dataSet);
                    }

                    MemberSession ms = new MemberSession()
                    {
                        id = (long)dataSet.Tables[0].Rows[0].ItemArray[0],
                        member_id = (long)dataSet.Tables[0].Rows[0].ItemArray[1],
                        member_email = dataSet.Tables[0].Rows[0].ItemArray[2].ToString(),
                        member_token = dataSet.Tables[0].Rows[0].ItemArray[3].ToString(),
                        FirstName = dataSet.Tables[0].Rows[0].ItemArray[4].ToString(),
                        session_start = (DateTime)dataSet.Tables[0].Rows[0].ItemArray[5],
                        IsActive = (bool)dataSet.Tables[0].Rows[0].ItemArray[6],
                        LastActive = (DateTime)dataSet.Tables[0].Rows[0].ItemArray[7],
                        SessionExpires = (DateTime)dataSet.Tables[0].Rows[0].ItemArray[8],
                        member_ip = dataSet.Tables[0].Rows[0].ItemArray[9].ToString(),
                    };
                    //get the member object
                    ms.IsActive = false;
                    SqlConnection sql4 = new SqlConnection(strConnection);
                    SqlCommand command4 = new SqlCommand();
                    command4.CommandText = @"dbo.usp_tbl_member_sessions_ups";
                    command4.CommandType = System.Data.CommandType.StoredProcedure;
                    SqlParameter p70 = new SqlParameter(@"member_id", ms.member_id);
                    SqlParameter p71 = new SqlParameter(@"member_email", ms.member_email);
                    SqlParameter p72 = new SqlParameter(@"member_token", ms.member_token);
                    SqlParameter p73 = new SqlParameter(@"member_name", ms.FirstName + @" " + ms.LastName);
                    SqlParameter p74 = new SqlParameter(@"session_start", ms.session_start);
                    SqlParameter p75 = new SqlParameter(@"session_active", false);
                    SqlParameter p76 = new SqlParameter(@"session_last_active", ms.LastActive);
                    SqlParameter p77 = new SqlParameter(@"session_end", ms.SessionExpires);
                    SqlParameter p78 = new SqlParameter(@"member_ip", ms.member_ip);
                    command4.Parameters.Add(p70);
                    command4.Parameters.Add(p71);
                    command4.Parameters.Add(p72);
                    command4.Parameters.Add(p73);
                    command4.Parameters.Add(p74);
                    command4.Parameters.Add(p75);
                    command4.Parameters.Add(p76);
                    command4.Parameters.Add(p77);
                    command4.Parameters.Add(p78);
                    long lngResult4 = 0;
                    using (sql4)
                    {
                        sql4.Open();
                        command4.Connection = sql4;
                        lngResult4 = (long)command4.ExecuteScalar();
                    }
                    if (lngResult4.Equals(0))
                    {
                        Controllers.ValuesController.LogIt(@"Error updating session on logout", @"Logout");
                    }

                    Response.Cookies.Delete(@"s3cr3tx");
                    
                }
                else
                {
                    _message = @"Please login again";
                    Response.Redirect(@"https://s3cr3tx.com/Login");
                }
            }
            catch (Exception ex)
            {
                //string strResult = @"";
                string strSource = @"s3cr3tx.api.RegisterPageCS.OnGet";
                s3cr3tx.Controllers.ValuesController.LogIt(ex.GetBaseException().ToString(), strSource);
                Redirect(@"https://s3cr3tx.com/Login");
            }
        }
    }
    }

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace s3cr3tx.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/API_Info.cshtml
@page
@model s3cr3tx.Pages.API_InfoModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "s3cretx API Info";
}
@section Login{
    <partial name="_LoginPartial" />
}
<div class="text-center">
    <center> <h1 class="display-4">Your s3cr3tx API Credentials are listed below</h1></center>
    <form asp-page-handler="view" formaction="post">
        <center>
            <table>
                <tr>
                    <td align="right">
                        <label id="lblEmail">Email: </label>
                    </td>
                    <td>
                        @Model.S3Cr3Tx.Email
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        <label id="lblToken">API Key: </label>
                    </td>
                    <td>
                        <textarea>@Model.S3Cr3Tx.Token</textarea>
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        <label id="lblAuth">Auth Code: </label>
                    </td>
                    <td>
                        <textarea>@Model.S3Cr3Tx.AuthCode</textarea>
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        <label id="lblAuth">Private Key Certificate (PEM Format): </label>
                    </td>
                    <td>
                        <textarea>@Model.S3Cr3Tx.PEMpri</textarea>


                    </td>
                </tr>
                <tr>
                    <td align="right">
                        <label id="lblAuth">Public Key Certificate (PEM Format): </label>
                    </td>
                    <td>
                        <textarea>@Model.S3Cr3Tx.PEMpub</textarea>
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        <label id="lblAuth8">Download a local s3cr3tx offline version and PEM Key: </label>
                    </td>
                    <td>
                        <label id="lblPass">Please enter a Password for your download: </label><br/>
                        <input id="txtEmail" asp-for="S3Cr3Tx.passcode" class="form-control" maxlength="256" />
                        <span asp-validation-for="S3Cr3Tx.passcode" class="text-danger"></span>
                        <br />
                        <input type="submit" id="btnSubmit" disabled="disabled" value="Download" />
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        <label id="lblAuth">Use the following command to generate your own keys for use with the s3cr3tx local version: </label>
                    </td>
                    <td>
                        
                        <label id="lblAuth" style="background-color:grey">openssl req -newkey rsa:4096 -nodes -keyout s3cr3txKey.pem -x509 -days 365 -out s3cr3txCertificate.pem</label>
                    </td>
                </tr>
            </table>
        </center>
        <br />
    </form>
</div>
@section sitescripts{
    <partial name="_SiteScriptsPartial" />
}

Pages/Forgot.cshtml
@page
@model ForgotModel
@{
    ViewData["Title"] = "Please enter your email address";
}
@section Members{
    <partial name="_LoginRegisterPartial" />
}
<h1>Please enter the email address associated with your s3cr3tx account:</h1>
<form asp-page-handler="view" formaction="post">
    <center>
        <table>
            <tr>
                <td align="right">
                    <label id="lblOutput">&nbsp;</label>
                </td>
                <td>
                    @Model._output
                </td>
            </tr>
            <tr>
                <td align="right">
                    <label id="lblEmail">Email: </label>
                </td>
                <td>
                    <input id="txtEmail" asp-for="forgotCurrent.member_email" maxlength="256" />
                </td>
            </tr>
            <tr>
                <td align="right">
                    <label id="lblInput">&nbsp;</label>
                </td>
                <td>
                    <input type="submit" id="btnSubmit"/>
                </td>
            </tr>
            <tr>
                <td align="right">
                    <label id="lblOutput2">&nbsp;</label>
                </td>
                <td>
                    @Model._output
                </td>
            </tr>
        </table>
    </center>
        </form>

<center>
    <h2><a href="https://s3cr3tx.com/Login">sign-in</a></h2>
</center>

            @section sitescripts{
                <partial name="_SiteScriptsPartial" />
            }

Pages/Freset.cshtml
@page
@model FresetModel
@{
    ViewData["Title"] = "Thank you for confirming your s3cr3tx account";
}
@section Members{
    <partial name="_LoginRegisterPartial" />
}
<h1>Please enter the details requested and click submit below</h1>
<form asp-page-handler="view" formaction="post">
    <center>
        <table>
            <tr>
                <td align="right">
                    <label id="lblOutput">&nbsp;</label>
                </td>
                <td>
                    @Model._output
                </td>
            </tr>
            <tr>
                <td align="right">
                    <label id="lblPWord">New Password: </label>
                </td>
                <td>
                    <input id="txtPWord" asp-for="fresetCurrent.member_code" maxlength="256" />
                </td>
            </tr>
            <tr>
                <td align="right">
                    <label id="lblPWord">Confirm New Password: </label>
                </td>
                <td>
                    <input id="txtPWord" asp-for="fresetCurrent.member_code2" maxlength="256" />
                </td>
            </tr>
            <tr>
                <td align="right">
                    <input id="txtEmail" asp-for="fresetCurrent.email" hidden="hidden"/>   </td>
                <td>
                    <input id="txtPWord" asp-for="fresetCurrent.session_expires" hidden="hidden" maxlength="256" />
                </td>
            </tr>
            <tr>
                <td align="right">
                    <label id="lblInput">&nbsp;</label>
                </td>
                <td>
                    <input type="submit" id="btnSubmit" disabled="disabled" />
                </td>
            </tr>
            <tr>
                <td align="right">
                    <label id="lblPWord">&nbsp; </label>
                </td>
                <td>
                    <input id="txtPWord" asp-for="fresetCurrent.id" maxlength="256" hidden="hidden"/>
                </td>
            </tr>
            <tr>
                <td align="right">
                    <label id="lblOutput2">&nbsp;</label>
                </td>
                <td>
                    @Model._output
                </td>
            </tr>
        </table>
    </center>
</form>

<center>
    <h2><a href="https://s3cr3tx.com/Login">sign-in</a></h2>
</center>

@section sitescripts{
    <partial name="_SiteScriptsPartial" />
}
@section scripts{
    <partial name="_ValidationScriptsPartial" />
}

Pages/Index.cshtml
@page
@model s3cr3tx.Pages.IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "s3cr3tx : helping you protect secrets in code";
}
@section Login{
    <partial name="_LoginPartial" />
}
<div class="text-center">
    <center>
        <br/>
        <h1 class="display-6">Welcome to s3cr3tx</h1>
        Use the form below to interact with s3cr3tx API
        <br />
        <br/>
    </center>
    <form asp-page-handler="view" formaction="post">
        <center>
            <table>
                <tr>
                    <td align="right">
                        <label id="lblEmail">Email: </label>
                    </td>
                    <td>
                        <input id="txtEmail" asp-for="S3Cr3Tx.Email" maxlength="256" />
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        <label id="lblToken">API Key: </label>
                    </td>
                    <td>
                        <input id="txtToken" maxlength="256" asp-for="S3Cr3Tx.Token" />
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        <label id="lblAuth">Auth Code: </label>
                    </td>
                    <td>
                        <input id="txtAuthCode" maxlength="256" asp-for="S3Cr3Tx.AuthCode" />
                    </td>

                </tr>
                <tr>
                    <td align="right">
                        <label id="lblDirection">Enter e to encrypt or d to decrypt: </label>
                    </td>
                    <td>
                        <input id="txtDirection" asp-for="S3Cr3Tx.EoD" maxlength="256" />
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        <label id="lblInput">Input: </label>
                    </td>
                    <td>
                        <textarea id="txtInput" asp-for="S3Cr3Tx.Input"></textarea>
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        <label id="lblInput">&nbsp;</label>
                    </td>
                    <td>
                        <input type="submit" id="btnSubmit" disabled="disabled" />
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        <label id="lblOutput">Output: </label>
                    </td>
                    <td rowspan="10" width="200"><textarea>@Model.S3Cr3Tx.Output</textarea></></td>
                </tr>
            </table>
        </center>

    </form>
    <center>
        <br/>
        <p>Our <a href="https://www.github.com/GratitechInc">GitHub</a> repos include examples of interacting with s3cr3tx API in Java, C#, Python, and Go</p>
        </p>
    </center>
</div>
@section sitescripts{
    <partial name="_SiteScriptsPartial" />
}

Pages/Logout.cshtml
@page
@model LogoutModel
@{
    ViewData["Title"] = "You have been signed out of s3cr3tx";
}
@section Members{
    <partial name="_LoginRegisterPartial" />
}
<h1>Thank you for visiting s3cr3tx.</h1>
<br/>
<h2>You have been signed out of s3cr3tx</h2>
@section sitescripts{
    <partial name="_SiteScriptsPartial" />
}

Pages/Validate.cshtml
@page
@model ValidateModel
@{
    ViewData["Title"] = "Thank you for confirming your s3cr3tx account";
}
@section Members{
    <partial name="_LoginRegisterPartial" />
}
<h1>Thank you for confirming your s3cr3tx account.</h1>
<h2>You can <a href="https://s3cr3tx.com/Login">sign-in</a> to s3cr3tx now</h2>
@section sitescripts{
    <partial name="_SiteScriptsPartial" />
}